version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: EmployeesDb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"  

  student_api:
    build: .
    container_name: student_api_container
    restart: always
    depends_on:
      - mysql
    environment:
      - ConnectionStrings__DefaultConnection=Server=mysql;Port=3306;Database=EmployeesDb;User=root;Password=rootpassword;
    ports:
      - "5000:5000" 
