name: StudentAPI-Deploy

on:
  push:
    branches:
      - main
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOSTNAME: ${{ secrets.EC2_HOST }}
          USER_NAME: ec2-user
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} << 'EOF'
            cd /home/ec2-user/Student_API-ec2/Student_API

            # Update code
            git fetch --all
            git reset --hard origin/master

            # Stop the running service
            sudo systemctl stop Student_API.service

            # Clean, build, and publish .NET app
            dotnet clean
            dotnet build --configuration Release
            dotnet publish -c Release -o /home/ec2-user/Student_API-ec2/publish

            # Restart the service
            sudo systemctl daemon-reload
            sudo systemctl restart Student_API.service
            sudo systemctl status Student_API.service
          EOF
